// ============================================================
//  ANIMAL MART — DEMO DATA
//  This is seed data for the demo. In production, replace with
//  API calls to your backend (see INTEGRATION-GUIDE.md).
// ============================================================
window.SEED_PRODUCTS = [
  // ---- DOG FOOD ----
  {id:'p01', name:'Royal Chompers Dry Food', cat:'Dog Food', pet:'dog', price:3499, old:4200, sold:1284, rating:5, img:'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=800&q=80', desc:'Protein-rich dry kibble crafted for adult dogs. Real chicken first ingredient, no fillers, glossy-coat omega blend.'},
  {id:'p02', name:'Puppy Power Starter Pack', cat:'Dog Food', pet:'dog', price:2899, old:3500, sold:932, rating:5, img:'https://images.unsplash.com/photo-1585846888147-3fe14c130048?w=800&q=80', desc:'Gentle, easy-to-digest formula for growing puppies. Packed with DHA for brain development.'},
  {id:'p03', name:'Beefy Bites Wet Food Tray', cat:'Dog Food', pet:'dog', price:1450, old:1800, sold:2103, rating:4, img:'https://images.unsplash.com/photo-1582798358481-d199fb7347bb?w=800&q=80', desc:'Slow-cooked beef chunks in savoury gravy. Twelve single-serve trays your dog will inhale.'},
  {id:'p04', name:'Grain-Free Salmon Feast', cat:'Dog Food', pet:'dog', price:3999, old:4600, sold:651, rating:5, img:'https://images.unsplash.com/photo-1568640347023-a616a30bc3bd?w=800&q=80', desc:'Wild-caught salmon recipe for sensitive tummies. Grain-free and gentle.'},
  // ---- CAT FOOD ----
  {id:'p05', name:'Whisker Licker Tuna Pâté', cat:'Cat Food', pet:'cat', price:1299, old:1600, sold:3195, rating:5, img:'https://images.unsplash.com/photo-1589927986089-35812388d1f4?w=800&q=80', desc:'Smooth tuna pâté cats go wild for. Grain-free, vet-approved, irresistibly fishy.'},
  {id:'p06', name:'Kitten Cloud Crunchies', cat:'Cat Food', pet:'cat', price:1899, old:2300, sold:1421, rating:5, img:'https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=800&q=80', desc:'Tiny crunchy bites sized for kitten mouths. Builds strong bones and shiny fur.'},
  {id:'p07', name:'Creamy Fish Oil Lickable Pump', cat:'Cat Food', pet:'cat', price:2497, old:2999, sold:5395, rating:5, img:'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=800&q=80', desc:'One-pump lickable treat loaded with omega-3. Keeps coats glossy and cats begging.'},
  {id:'p08', name:'Indoor Cat Hairball Formula', cat:'Cat Food', pet:'cat', price:2199, old:2700, sold:880, rating:4, img:'https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=800&q=80', desc:'Fibre-rich kibble that helps reduce hairballs for indoor loungers.'},
  // ---- DOG TOYS ----
  {id:'p09', name:'ChompClean Dental Toy', cat:'Dog Toys', pet:'dog', price:2197, old:2697, sold:3195, rating:5, img:'https://images.unsplash.com/photo-1535930891776-0c2dfb7fda1a?w=800&q=80', desc:'Chewy textured toy that cleans teeth while they play. Tough, bouncy, dishwasher safe.'},
  {id:'p10', name:'Tug-o-War Rope Braid', cat:'Dog Toys', pet:'dog', price:899, old:1200, sold:2780, rating:5, img:'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=800&q=80', desc:'Hand-knotted cotton rope for endless tug battles. Floats in water too.'},
  {id:'p11', name:'Squeaky Plush Duck', cat:'Dog Toys', pet:'dog', price:1100, old:1400, sold:1955, rating:4, img:'https://images.unsplash.com/photo-1591946614720-90a587da4a36?w=800&q=80', desc:'Soft plush duck with a satisfying squeak. The cuddle-and-carry favourite.'},
  {id:'p12', name:'Treat Puzzle Ball', cat:'Dog Toys', pet:'dog', price:1699, old:2100, sold:1340, rating:5, img:'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800&q=80', desc:'Hide treats inside and watch them work it out. Beats boredom, slows fast eaters.'},
  // ---- CAT TOYS ----
  {id:'p13', name:'CandyKick Catnip Kicker', cat:'Cat Toys', pet:'cat', price:2997, old:3599, sold:782, rating:5, img:'https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=800&q=80', desc:'Catnip-stuffed kicker for bunny-kick frenzies. Crinkles, crunches, and never quits.'},
  {id:'p14', name:'Feather Wand Teaser', cat:'Cat Toys', pet:'cat', price:799, old:1100, sold:4120, rating:5, img:'https://images.unsplash.com/photo-1574231164645-d6f0e8553590?w=800&q=80', desc:'Flutter feathers on a flexible wand. Sparks the hunt instinct every single time.'},
  {id:'p15', name:'Crinkle Tunnel Burrow', cat:'Cat Toys', pet:'cat', price:2399, old:2900, sold:1670, rating:4, img:'https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=800&q=80', desc:'Collapsible crinkle tunnel for ambush games and cosy hideouts.'},
  {id:'p16', name:'Spinning Ball Track', cat:'Cat Toys', pet:'cat', price:1999, old:2500, sold:2240, rating:5, img:'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?w=800&q=80', desc:'Three-tier track with whirling balls. Solo-play genius for indoor cats.'},
  // ---- ACCESSORIES ----
  {id:'p17', name:'CozyClaw Plush Bed Mat', cat:'Beds', pet:'cat', price:3597, old:4797, sold:2453, rating:5, img:'https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=800&q=80', desc:'Plush supportive mat for kneading, lounging, and deep naps. Protects your sofa too.'},
  {id:'p18', name:'Orthopedic Dog Lounger', cat:'Beds', pet:'dog', price:5499, old:6800, sold:540, rating:5, img:'https://images.unsplash.com/photo-1541599540903-216a46ca1dc0?w=800&q=80', desc:'Memory-foam lounger for achy joints and giant snoozes. Washable cover.'},
  {id:'p19', name:'Adjustable Comfort Harness', cat:'Accessories', pet:'dog', price:2299, old:2900, sold:1180, rating:4, img:'https://images.unsplash.com/photo-1567014543648-e4391c989aab?w=800&q=80', desc:'No-pull padded harness for happy walks. Five points of adjustment.'},
  {id:'p20', name:'Stainless Slow-Feed Bowl', cat:'Accessories', pet:'dog', price:1399, old:1800, sold:990, rating:5, img:'https://images.unsplash.com/photo-1591769225440-811ad7d6eab3?w=800&q=80', desc:'Maze-bottom bowl that slows gulpers and aids digestion. Rust-proof steel.'},
  {id:'p21', name:'Self-Cleaning Litter Scoop', cat:'Accessories', pet:'cat', price:1599, old:2000, sold:1310, rating:4, img:'https://images.unsplash.com/photo-1606214174585-fe31582dc6ee?w=800&q=80', desc:'Ergonomic sifting scoop that keeps litter duty quick and tidy.'},
  {id:'p22', name:'Calming Cuddle Donut Bed', cat:'Beds', pet:'cat', price:3199, old:3999, sold:2080, rating:5, img:'https://images.unsplash.com/photo-1518288774672-b94e808873ff?w=800&q=80', desc:'Faux-fur donut bed with a raised rim for secure, anxiety-easing snuggles.'},
  {id:'p23', name:'Reflective Bell Collar', cat:'Accessories', pet:'cat', price:699, old:950, sold:3400, rating:5, img:'https://images.unsplash.com/photo-1574144611937-0df059b5ef3e?w=800&q=80', desc:'Safety-release collar with reflective stitching and a soft jingle bell.'},
  {id:'p24', name:'Travel Carrier Backpack', cat:'Accessories', pet:'cat', price:4299, old:5200, sold:760, rating:5, img:'https://images.unsplash.com/photo-1623387641168-d9803ddd3f35?w=800&q=80', desc:'Ventilated bubble backpack for vet trips and adventures. Airline-friendly.'}
];

window.SEED_REVIEWS = [
  {id:'r1', name:'Denise', product:'CandyKick Catnip Kicker', rating:5, text:'My cat played with it, threw it around, bit it and had endless fun. Worth every rupee!', verified:true},
  {id:'r2', name:'Hamza', product:'ChompClean Dental Toy', rating:5, text:'My Labrador is obsessed. His breath actually improved after two weeks of chewing.', verified:true},
  {id:'r3', name:'Ayesha', product:'CozyClaw Plush Bed Mat', rating:5, text:'Took it out, laid it down, and she immediately curled up and slept. A throne for my princess.', verified:true},
  {id:'r4', name:'Bilal', product:'Royal Chompers Dry Food', rating:5, text:'Switched my two dogs to this and their coats are shinier. Delivery was fast across Lahore.', verified:true},
  {id:'r5', name:'Sana', product:'Creamy Fish Oil Lickable Pump', rating:5, text:'The only treat that gets all three cats running to the kitchen. Helps with shedding too.', verified:true},
  {id:'r6', name:'Fatima', product:'Feather Wand Teaser', rating:4, text:'Simple but my kitten cannot resist it. Great value for an evening of zoomies.', verified:true}
];

window.SEED_ARTICLES = [
  {id:'a1', title:'How to Switch Your Dog to a New Food (Without the Tummy Trouble)', tag:'Nutrition', read:'4 min', featured:true, img:'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=1200&q=80', excerpt:'A gradual seven-day transition keeps digestion happy. Here is the day-by-day mix ratio vets recommend.', body:'Switching food too fast is the number one cause of upset stomachs. Start with 25% new food mixed into 75% old for two days, move to a 50/50 split for the next two, then 75% new for two more, and finally 100% on day seven. Watch stool consistency at each step — if things get loose, hold at the current ratio an extra day before moving on. Always keep fresh water available, and choose a calm week without other big changes so you can spot what your dog is reacting to.'},
  {id:'a2', title:'Why Cats Love Boxes, Tunnels and Tiny Hiding Spots', tag:'Behaviour', read:'3 min', featured:true, img:'https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=1200&q=80', excerpt:'It is not random. Enclosed spaces tap into a deep instinct for safety and ambush play.', body:'Cats are both predator and prey, and tight enclosed spaces satisfy both sides of that wiring. A box or tunnel offers a defensible vantage point to watch the room, a cosy temperature pocket, and the perfect ambush launchpad for play. Providing a crinkle tunnel or a covered bed reduces stress in multi-cat homes and gives shy cats a retreat. The result is a calmer, more confident cat who plays more and hides-from-fear less.'},
  {id:'a3', title:'The 10-Minute Daily Play Routine Every Indoor Pet Needs', tag:'Wellness', read:'5 min', featured:false, img:'https://images.unsplash.com/photo-1574231164645-d6f0e8553590?w=1200&q=80', excerpt:'Short, structured play beats a single long session. Build the habit in three easy blocks.', body:'Indoor pets burn far less energy than their outdoor cousins, and pent-up energy turns into chewing, scratching, and 3am zoomies. The fix is short structured play: two five-minute bursts of wand or fetch in the morning and evening, ending each session with a small treat so the game has a satisfying finish. Rotate two or three toys weekly so novelty stays high. Consistency matters more than duration.'},
  {id:'a4', title:'Reading Pet Food Labels: What Actually Matters', tag:'Nutrition', read:'6 min', featured:false, img:'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=1200&q=80', excerpt:'Ingredient order, named proteins, and the difference between "meal" and "by-product".', body:'The first ingredient should be a named protein like chicken or salmon, not a vague "meat" or "animal derivative". Ingredients are listed by weight, so the top three tell you most of the story. "Meal" is concentrated and fine; "by-product" quality varies widely. Look for guaranteed analysis numbers for protein and fat that match your pet life stage, and treat long lists of unpronounceable additives with healthy suspicion.'}
];
